# Generated by Django 6.0 on 2026-01-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='prompt_id',
        ),
    ]
