# Generated by Django 6.0.1 on 2026-01-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_aimodel_prompt_models_supported'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
