# Generated by Django 6.0.1 on 2026-02-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_prompt_is_public_prompt_updated_at_prompt_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
