# Generated by Django 6.0.1 on 2026-02-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_remove_prompt_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
