# Generated by Django 6.0.1 on 2026-02-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_prompt_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='is_public',
        ),
        migrations.AddField(
            model_name='prompt',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
