# Generated by Django 6.0.1 on 2026-02-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='subject',
        ),
    ]
