# Generated by Django 6.0.1 on 2026-02-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_remove_contactus_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='instructions',
        ),
    ]
