# Generated by Django 6.0.1 on 2026-02-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_remove_prompt_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptUploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prompts/')),
            ],
        ),
    ]
