# Generated by Django 6.0.1 on 2026-02-03 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_promptuploadimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prompt_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Home.prompt')),
            ],
        ),
        migrations.DeleteModel(
            name='PromptUploadImage',
        ),
    ]
