# Generated by Django 6.0.1 on 2026-02-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_promptimage_delete_promptuploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromptImage',
        ),
    ]
