# Generated by Django 6.0 on 2026-02-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_delete_promptimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactus',
            new_name='Contact',
        ),
    ]
